server:
  port: ${PORT:8080}
  servlet:
    context-path: /manager-image

spring:
  application:
    name: manager-image
  servlet:
    multipart:
      max-file-size: 500MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: file
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    schemas:
      - file
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: us-east-1
    s3:
      bucket-name: ${BUCKET_S3_NAME}
      uri: ${BASE_URL_AWS_S3}+${BUCKET_S3_NAME}